sudo: required
language: python
services:
  - docker
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install nose coverage
script:
  - make static
  - make test
  - docker build -t spacewiki .
